name: "Megaphone APP CI"

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  push:
    paths:
      - 'src/megaphone.app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/megaphone.app/**'

jobs:
   build:
    name: Megaphone CI
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: '5.0.103'
        source-url: https://nuget.pkg.github.com/AlexandreBrisebois/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: restore
      run: dotnet restore "./src/megaphone.app.sln"

    - name: build
      run: dotnet build "./src/megaphone.app.sln" --no-restore -c Release